# fly.toml app configuration file generated for roland-kraut on 2023-11-25T19:48:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "roland-kraut"
primary_region = "ewr"

[build]

[[services]]
  internal_port = 8080      # internal HTTP port
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = "80"             # HTTP port

  [[services.ports]]
    handlers = ["http", "tls"]
    port = "443"            # HTTPS port